Repository opynfinance/GammaProtocol, pull requests merged in 2020-10, with the labels that each got.

#269 Update event parameter name in SystemPaused
  contracts/Controller.sol
Labels: enhancement

#271 Certora: fix rules
  .gitignore
  contracts/libs/MarginVault.sol
  specs/MarginVault.spec
  test/unit-tests/marginVault.test.ts
Labels: certora

#274 Add check for long != short in a vault
  contracts/MarginCalculator.sol
  test/unit-tests/marginCalculator.test.ts
Labels: bug
