Repository opynfinance/GammaProtocol, pull requests merged in 2020-11, with the labels that each got.

#290 [M01] oToken can be created with a non-whitelisted collateral asset
  contracts/Whitelist.sol
  test/integration-tests/longCallSpreadExpireItm.test.ts
  test/integration-tests/longCallSpreadExpireOtm.test.ts
  test/integration-tests/longCallSpreadPreExpiry.test.ts
  test/integration-tests/longPutExpireItm.test.ts
  test/integration-tests/longPutExpireOtm.test.ts
  test/integration-tests/longPutPreExpiry.test.ts
  test/integration-tests/nakedCallExpireItm.test.ts
  test/integration-tests/nakedCallExpireOtm.test.ts
  test/integration-tests/nakedCallPreExpiry.test.ts
  test/integration-tests/nakedPutExpireITM.test.ts
  test/integration-tests/nakedPutExpireOTM.test.ts
  test/integration-tests/nakedPutPreExpiry.test.ts
  test/integration-tests/open-markets.test.ts
  test/integration-tests/rollover.test.ts
  test/integration-tests/shortCallSpreadExpireItm.test.ts
  test/integration-tests/shortCallSpreadExpireOtm.test.ts
  test/integration-tests/shortCallSpreadPreExpiry.test.ts
  test/integration-tests/shortPutSpreadExpireItm.test.ts
  test/integration-tests/shortPutSpreadExpireOtm.test.ts
  test/integration-tests/shortPutSpreadPreExpiry.test.ts
  test/integration-tests/yieldFarming.test.ts
  test/unit-tests/Whitelist.test.ts
Labels: audit-fix-phase1

#292 [L01] Disputer can dispute a price before a pricer has submitted a price
  contracts/Oracle.sol
  test/unit-tests/oracle.test.ts
Labels: audit-fix-phase1

#298 [N01] Functions default to a particular case
  contracts/Controller.sol
Labels: audit-fix-phase1

#287 [L07] Mismatches between contracts and interfaces
  contracts/interfaces/MarginCalculatorInterface.sol
  contracts/interfaces/MarginPoolInterface.sol
  contracts/interfaces/OracleInterface.sol
  contracts/interfaces/OtokenInterface.sol
  contracts/interfaces/WhitelistInterface.sol
Labels: audit-fix-phase1

#289 [L05] Lack of input validation could pollute the event logs
  contracts/Controller.sol
  test/unit-tests/controller.test.ts
Labels: audit-fix-phase1

#291 [M03] Actions are undefined at the exact time of oToken expiry
  contracts/Controller.sol
Labels: audit-fix-phase1

#295 [L10] String is used as hash key
  contracts/AddressBook.sol
  test/unit-tests/addressBook.test.ts
Labels: audit-fix-phase1

#286 [L04] Lack of indexed parameters in events
  contracts/AddressBook.sol
  contracts/MarginPool.sol
  contracts/Oracle.sol
  contracts/OtokenFactory.sol
Labels: audit-fix-phase1

#297 [L09] oToken symbols might not be unique
  contracts/Otoken.sol
  test/integration-tests/open-markets.test.ts
  test/unit-tests/Otoken.test.ts
  test/unit-tests/oracle.test.ts
Labels: audit-fix-phase1

#302 [N06] Typographical errors and misleading comments
  contracts/AddressBook.sol
  contracts/MarginCalculator.sol
  contracts/Oracle.sol
  contracts/Whitelist.sol
  contracts/libs/MarginVault.sol
  contracts/mocks/MockWhitelistModule.sol
  docs/contracts-documentation/Whitelist.md
  docs/contracts-documentation/mocks/MockWhitelistModule.md
  docs/uml/GammaUML.svg
  docs/uml/GammaWhitelist.svg
  test/unit-tests/Whitelist.test.ts
  test/unit-tests/controller.test.ts
  test/unit-tests/oracle.test.ts
Labels: audit-fix-phase1

#285 [L02] Constants are not being declared explicitly
  contracts/MarginCalculator.sol
  contracts/OtokenFactory.sol
Labels: audit-fix-phase1

#288 [L03] Operations are not explicitly casted
  contracts/MarginCalculator.sol
  contracts/OtokenSpawner.sol
  contracts/pricers/CompoundPricer.sol
Labels: audit-fix-phase1

#266 Certora initial specs
  .circleci/config.yml
  .gitignore
  contracts/libs/MarginVault.sol
  specs/MarginVault.spec
  specs/MarginVaultHarness.sol
  specs/Privileged.spec
  specs/runMarginVault.sh
  specs/whitelist/expected.json
  specs/whitelist/runPrivilegedWhitelist.sh
  test/unit-tests/marginVault.test.ts
Labels: certora, v0.2.0

#301 [C01] An attacker can steal all the collateral assets
  contracts/Controller.sol
  test/unit-tests/controller.test.ts
Labels: audit-fix-phase1

#299 [N03] Refactoring opportunities
  contracts/AddressBook.sol
  contracts/Controller.sol
  contracts/MarginCalculator.sol
  contracts/OtokenFactory.sol
Labels: audit-fix-phase1

#306 Remove USDC pricer and integrate stable prices into Oracle module
  contracts/Oracle.sol
  contracts/pricers/USDCPricer.sol
  test/unit-tests/chainlinkPricer.test.ts
  test/unit-tests/oracle.test.ts
  test/unit-tests/usdcPricer.test.ts
Labels: v0.2.0

#305 [M04]: Use of transfer might render ETH impossible to withdraw
  contracts/external/proxies/PayableProxyController.sol
Labels: audit-fix-phase1

#309 Fix chainlink pricer
  contracts/pricers/ChainlinkPricer.sol
  specs/MarginVaultHarness.sol
  specs/whitelist/expected.json
  test/integration-tests/pricer-oracle.test.ts
  test/unit-tests/chainlinkPricer.test.ts
Labels: v0.2.0

#304 [H01] ETH could get trapped in the protocol
  contracts/Controller.sol
  contracts/external/wrapper/FlashWrap.sol
  contracts/tests/FlashUnwrap.sol
  test/unit-tests/flashUnwrap.test.ts
Labels: audit-fix-phase1

#307 Refactor Call action
  contracts/Controller.sol
  contracts/interfaces/CalleeInterface.sol
  contracts/libs/Actions.sol
  contracts/tests/CallTester.sol
  contracts/tests/FlashUnwrap.sol
  test/unit-tests/Actions.test.ts
  test/unit-tests/controller.test.ts
Labels: v0.2.0

#311 Checks when adding pricer or stable price
  contracts/Oracle.sol
  test/unit-tests/oracle.test.ts
Labels: v0.2.0

#310 Fix Compound pricer
  contracts/Oracle.sol
  contracts/mocks/MockOracle.sol
  contracts/pricers/CompoundPricer.sol
  test/integration-tests/pricer-oracle.test.ts
  test/integration-tests/yieldFarming.test.ts
  test/unit-tests/compoundPricer.test.ts
  test/unit-tests/controller.test.ts
  test/unit-tests/oracle.test.ts
Labels: v0.2.0

#279 Feature: 0x callee and updates for PayableProxy
  .circleci/config.yml
  contracts/external/callees/Trade0x.sol
  contracts/external/proxies/PayableProxyController.sol
  contracts/interfaces/CalleeInterface.sol
  contracts/interfaces/ZeroXExchangeInterface.sol
  contracts/mocks/Mock0xERC20Proxy.sol
  contracts/mocks/Mock0xExchange.sol
  contracts/tests/CalleeAllowanceTester.sol
  contracts/tests/FlashUnwrap.sol
  package.json
  test/e2e/0xCallee.ts
  test/unit-tests/payableProxyController.test.ts
  test/unit-tests/trade0xCallee.test.ts
Labels: contract
