Repository opynfinance/GammaProtocol, pull requests merged in 2020-07, with the labels that each got.

#16 Add Otoken interface
  contracts/interfaces/OtokenInterface.sol
Labels: structure

#23 ETH gas reporter setup
  .circleci/config.yml
  .gitignore
  codechecks.yml
  package-lock.json
  package.json
  truffle-config.js
Labels: cicd

#22 Change OZ folder structure.
  .solcover.js
  contracts/MathTester.sol
  contracts/packages/oz/Address.sol
  contracts/packages/oz/IERC20.sol
  contracts/packages/oz/SafeMath.sol
  contracts/packages/oz/upgradeability/ERC20Initializable.sol
Labels: structure

#20 Update git hook.
  package.json
Labels: cicd

#19 Whitelist otoken
  contracts/Whitelist.sol
  contracts/interfaces/AddressBookInterface.sol
  contracts/mocks/MockAddressBook.sol
  test/Whitelist.test.ts
Labels: contract

#25 Whitelist collateral functionality
  contracts/Whitelist.sol
  package.json
  test/Whitelist.test.ts
Labels: contract

#18 Add MarginPool interface
  contracts/interfaces/MarginPoolInterface.sol
Labels: structure

#15 Add Whitelist Interface
  contracts/interfaces/WhitelistInterface.sol
Labels: structure

#17 Add AddressBook interface
  contracts/interfaces/AddressBookInterface.sol
Labels: structure

#27 Show USD in gas report
  package-lock.json
  truffle-config.js
Labels: cicd

#6 OTokenFactory Module
  .circleci/config.yml
  .solcover.js
  contracts/OtokenFactory.sol
  contracts/OtokenSpawner.sol
  contracts/interfaces/.gitkeep
  contracts/mocks/.gitkeep
  contracts/mocks/MockAddressBook.sol
  contracts/mocks/MockOtoken.sol
  contracts/mocks/MockWhitelistModule.sol
  contracts/packages/Spawn.sol
  contracts/packages/oz/.gitkeep
  contracts/packages/oz/Create2.sol
  package-lock.json
  test/OtokenFactory.test.ts
Labels: contract

#31 Otoken: Burn and Mint
  contracts/Otoken.sol
  contracts/mocks/MockAddressBook.sol
  test/Otoken.test.ts
Labels: contract

#29 DepositArgs Actions
  contracts/libs/Actions.sol
  contracts/mocks/ActionTester.sol
  package.json
  test/Actions.test.ts
Labels: contract

#41 Actions Module: Open Vault Args
  contracts/libs/Actions.sol
  contracts/mocks/ActionTester.sol
  contracts/packages/oz/Strings.sol
  test/Actions.test.ts
Labels: contract

#52 Task update interfaces
  contracts/interfaces/AddressBookInterface.sol
  contracts/interfaces/OtokenInterface.sol
Labels: contract
