Repository opynfinance/GammaProtocol, pull requests merged in 2021-02, with the labels that each got.

#362 Certora - support new more concise syntax for summaries
  specs/NoBankruptcy.spec
  specs/ValidBalances.spec
  specs/controller.spec
Labels: certora

#360 Add getOtokenDetails()
  .circleci/config.yml
  contracts/Controller.sol
  contracts/MarginCalculator.sol
  contracts/Otoken.sol
  contracts/interfaces/OtokenInterface.sol
  contracts/mocks/MockOtoken.sol
  specs/ValidBalances.spec
  specs/harness/ControllerHarness.sol
  test/unit-tests/Otoken.test.ts
Labels: gamma-v1.1.0

#363 [PVE-002] Fix expiry check in Calculator
  contracts/MarginCalculator.sol
Labels: audit-fix-phase2, gamma-v1.1.0, peckshield
