Repository opynfinance/GammaProtocol, pull requests merged in 2021-05, with the labels that each got.

#395 YearnPricer
  contracts/interfaces/YearnVaultInterface.sol
  contracts/mocks/MockYToken.sol
  contracts/pricers/YearnPricer.sol
  package-lock.json
  test/unit-tests/yearnPricer.test.ts
  test/utils.ts
Labels: pricer

#398 Update _isMarginableLong() verifications order
  contracts/MarginCalculator.sol
Labels: gamma-v2.0.0

#399 Add donate feature
  contracts/Controller.sol
  test/unit-tests/controller.test.ts
Labels: gamma-v2.0.0

#397 Disable withdrawing collateral after expiry
  contracts/Controller.sol
  test/integration-tests/nakedMarginCallPreExpiry.test.ts
  test/integration-tests/nakedMarginPutPreExpiry.test.ts
  test/unit-tests/controller.test.ts
  test/unit-tests/controllerNakedMargin.test.ts
Labels: gamma-v2.0.0

#400 Add public getMarginRequired()
  contracts/MarginCalculator.sol
Labels: gamma-v2.0.0

#401 Rename state variables
  contracts/MarginCalculator.sol
Labels: gamma-v2.0.0

#402 Update yearn pricer
  contracts/pricers/YearnPricer.sol
Labels: gamma-v2.0.0, pricer

#407 Fix: nakedMarginPutPreExpiry assertion
  test/integration-tests/nakedMarginPutPreExpiry.test.ts
Labels: gamma-v2.0.0, test

#412 Fix: Integration test assertions
  test/integration-tests/nakedMarginCallPreExpiry.test.ts
  test/integration-tests/nakedMarginPutPreExpiry.test.ts
Labels: gamma-v2.0.0, test
